// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// CHANGE
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQaRAypTyKWM4XBa7UbYcA6S_nvy7srcM',
    appId: '1:223357936606:web:b3206379246977f3eb734f',
    messagingSenderId: '223357936606',
    projectId: 'dollar-dollar',
    authDomain: 'dollar-dollar.firebaseapp.com',
    storageBucket: 'dollar-dollar.appspot.com',
    measurementId: 'G-J2QNK93VR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy3Y07KFGyyADqLe3LSZay4yoYTMV5ky8',
    appId: '1:223357936606:android:203b0bd7845ce258eb734f',
    messagingSenderId: '223357936606',
    projectId: 'dollar-dollar',
    storageBucket: 'dollar-dollar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWic2yT_lvwO6IxpRYKqXdvx0Zxif0sJk',
    appId: '1:223357936606:ios:2d6a386423d1e322eb734f',
    messagingSenderId: '223357936606',
    projectId: 'dollar-dollar',
    storageBucket: 'dollar-dollar.appspot.com',
    iosClientId: '223357936606-6rt9fqnvspkho4qr86fvu0uv6ns084uk.apps.googleusercontent.com',
    iosBundleId: 'com.JonahVeit.dollarDollar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWic2yT_lvwO6IxpRYKqXdvx0Zxif0sJk',
    appId: '1:223357936606:ios:2d6a386423d1e322eb734f',
    messagingSenderId: '223357936606',
    projectId: 'dollar-dollar',
    storageBucket: 'dollar-dollar.appspot.com',
    iosClientId: '223357936606-6rt9fqnvspkho4qr86fvu0uv6ns084uk.apps.googleusercontent.com',
    iosBundleId: 'com.JonahVeit.dollarDollar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQaRAypTyKWM4XBa7UbYcA6S_nvy7srcM',
    appId: '1:223357936606:web:55e7005d3ea0f345eb734f',
    messagingSenderId: '223357936606',
    projectId: 'dollar-dollar',
    authDomain: 'dollar-dollar.firebaseapp.com',
    storageBucket: 'dollar-dollar.appspot.com',
    measurementId: 'G-VFNM0ZVKH8',
  );
}
